# Generated by Django 4.1.5 on 2023-01-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('video_id',), name='unique_videoId_youtube'),
        ),
    ]
